### ISSUE TITLE
Implement `starknet.rs` support for transaction endpoints

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/rpc-request-builder#13]
Implement autogenerated `starknet.rs` support for the following endpoints.

- `starknet_getTransactionStatus`
- `starknet_getTransactionByHash`
- `starknet_getTransactionByBlockIdAndIndex`
- `starknet_getTransactionReceipt`
- `starknet_getBlockTransactionCount`
- `starknet_getEvents`

**Additional Context:**

- https://github.com/NethermindEth/rpc-request-builder/issues/2
- https://github.com/NethermindEth/rpc-request-builder/blob/main/src/api/rpcspec/methods.ts

**Comment by dhirajs0** [comment]
Hi, I would like to work on this issue.

**Comment by jelilat** [comment]
> Hi, I would like to work on this issue.

Assigned to you @dhirajs0

**Comment by dhirajs0** [comment]
Great, working on it. Thanks
