### ISSUE TITLE
Implement `starknet.rs` support for block endpoints

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/rpc-request-builder#14]
Implement autogenerated `starknet.rs` support for the following endpoints.

- `starknet_getBlockWithTxHashes`
- `starknet_getBlockWithTxs`
- `starknet_blockNumber`
- `starknet_blockHashAndNumber`
- `starknet_getStateUpdate`
- `starknet_getStorageAt`

**Additional Context:**

- https://github.com/NethermindEth/rpc-request-builder/issues/2
- https://github.com/NethermindEth/rpc-request-builder/blob/main/src/api/rpcspec/methods.ts

**Comment by Prabhat1308** [comment]
Hi . I will be working on this.
