### ISSUE TITLE
Implement `starknet.rs` support for write endpoints

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/rpc-request-builder#16]
Implement autogenerated `starknet.rs` support for the following endpoints.

- `starknet_addInvokeTransaction`
- `starknet_addDeployAccountTransaction`

**Additional Context:**

- https://github.com/NethermindEth/rpc-request-builder/issues/2
- https://github.com/NethermindEth/rpc-request-builder/blob/main/src/api/rpcspec/methods.ts

**Comment by malik672** [comment]
@jelilat assign this to me

**Comment by malik672** [comment]
deploy account, can you expatiate more, is it to deploy the account or deploy contract

**Comment by 0xkyng** [comment]
Has this issue been solved?

**Comment by malik672** [comment]
> Has this issue been solved?

I've been assigned, will make a pr tonight,
