### ISSUE TITLE
Implement `starknet.rs` support for trace endpoints

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/rpc-request-builder#17]
Implement autogenerated `starknet.rs` support for the following endpoints.

- `starknet_traceTransaction`
- `starknet_traceBlockTransactions`
- `starknet_simulateTransactions`

**Additional Context:**

- https://github.com/NethermindEth/rpc-request-builder/issues/2
- https://github.com/NethermindEth/rpc-request-builder/blob/main/src/api/rpcspec/methods.ts

**Comment by malik672** [comment]
@jelilat assign this to me

**Comment by saimeunt** [comment]
Hey, following up on #20 I'd like to work on this one if possible.

**Comment by jelilat** [comment]
> @jelilat assign this to me

@malik672 assigned https://github.com/NethermindEth/rpc-request-builder/issues/18 to you

**Comment by jelilat** [comment]
> Hey, following up on #20 I'd like to work on this one if possible.

@saimeunt Assigned this to you

**Comment by saimeunt** [comment]
#20 fixes this issue.
