### ISSUE TITLE
Implement `starknet.go` support for block endpoints

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/rpc-request-builder#8]
Add autogenerated `starknet.go` code for the following endpoints.

- `starknet_getBlockWithTxHashes`
- `starknet_getBlockWithTxs`
- `starknet_blockNumber`
- `starknet_blockHashAndNumber`
- `starknet_getStateUpdate`
- `starknet_getStorageAt`

**Additional Context:**

- https://github.com/NethermindEth/rpc-request-builder/issues/1
- https://github.com/NethermindEth/rpc-request-builder/blob/main/src/api/rpcspec/methods.ts

**Comment by dhirajs0** [comment]
@jelilat I would like to take this issue, please assign it to me.

**Comment by Richa-iitr** [comment]
Hey @dhirajs0,
If you haven't started with the work, can i take up this task? I didn't see the assignment, and have already implemented the feature.

**Comment by dhirajs0** [comment]
> Hey @dhirajs0, @jelilat 
> If @dhirajs0  haven't started with the work, can i take up this task? I didn't see the assignment, and have already implemented the feature. 

Working on it, will create a PR by today :)

**Comment by Richa-iitr** [comment]
Thanks a lot :)
